---
version: '3.7'
services:
  mongodb:
    image: ${MONGO_IMAGE:-mongo:4.2}
    ports:
      - '27017:27017'
  wasteless-app:
    build:
      context: .
      args:
        JAR_FILE: ./app/target/wasteless-app-*-SNAPSHOT.jar
    image: wasteless/backend-app:latest
    ports:
      - '8080:8080'
    depends_on:
      - mongodb